import { Link } from 'react-router-dom'

export default function Terms() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      <Link to="/" className="text-sm text-blue-600 dark:text-blue-400 hover:underline mb-6 inline-block">
        ← Back to home
      </Link>
      <h1 className="text-2xl font-bold mb-6">Terms of Service</h1>
      <div className="space-y-6 text-sm text-gray-700 dark:text-gray-300">
        <section>
          <h2 className="text-base font-semibold mb-2">AI-generated content</h2>
          <p>
            Character maps are generated by AI and may contain errors, omissions, or inaccuracies.
            Character Map Generator makes no warranty that the generated content is accurate,
            complete, or up to date. Treat maps as a starting point, not a reference.
          </p>
        </section>
        <section>
          <h2 className="text-base font-semibold mb-2">No affiliation</h2>
          <p>
            This service is not affiliated with, endorsed by, or representing any author,
            publisher, studio, or actor described in the generated content.
          </p>
        </section>
        <section>
          <h2 className="text-base font-semibold mb-2">Service provided as-is</h2>
          <p>
            Character Map Generator is a hobby project provided without warranty or
            service-level commitment. It may be unavailable, slow, or produce wrong results.
          </p>
        </section>
        <section>
          <h2 className="text-base font-semibold mb-2">Reasonable use</h2>
          <p>
            Rate limits apply per IP address. Attempts to circumvent them are considered abuse and
            may result in blocks. The service is intended for personal and educational use.
          </p>
        </section>
        <section>
          <h2 className="text-base font-semibold mb-2">Copyright</h2>
          <p>
            Generated maps describe characters and relationships from existing works in the style
            of a reference card — fair-use territory for personal and educational use. Commercial
            republication of generated maps may require consideration of the underlying works'
            licenses.
          </p>
        </section>
        <section>
          <h2 className="text-base font-semibold mb-2">Attribution</h2>
          <p>
            This product uses the TMDB API but is not endorsed or certified by TMDB. Headshots,
            cast credits, and adaptation data come from{' '}
            <a
              href="https://www.themoviedb.org"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 dark:text-blue-400 hover:underline"
            >
              TMDb
            </a>
            . Book metadata comes from{' '}
            <a
              href="https://openlibrary.org"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-600 dark:text-blue-400 hover:underline"
            >
              Open Library
            </a>
            . The chosen AI model's name appears on the map's footer.
          </p>
        </section>
      </div>
    </main>
  )
}
