import json
import pytest
from pydantic import ValidationError
from app.models.character_map import CharacterMap, RefusalResponse

VALID_CHARACTER_MAP = {
    "title": "Congo",
    "subtitle": "Michael Crichton, 1980",
    "blurb": "A scientific expedition into the Congo Basin.",
    "spoiler_mode": "full",
    "factions": [
        {
            "id": "erts",
            "label": "ERTS Expedition",
            "description": "The primary expedition team.",
            "color_hint": "blue",
        }
    ],
    "characters": [
        {
            "id": "peter_elliot",
            "name": "Peter Elliot",
            "role": "Primatologist",
            "description": "A UC Berkeley professor leading the gorilla research.",
            "faction_id": "erts",
            "importance": "protagonist",
            "is_deceased_in_work": False,
            "spoiler_level": 0,
        }
    ],
    "relationships": [
        {
            "from_id": "peter_elliot",
            "to_id": "peter_elliot",
            "type": "professional",
            "label": "leads",
            "spoiler_level": 0,
        }
    ],
    "notes": "Full-spoiler map generated by Character Map Generator.",
}


def test_valid_map_parses():
    result = CharacterMap.model_validate(VALID_CHARACTER_MAP)
    assert result.title == "Congo"
    assert len(result.characters) == 1
    assert result.characters[0].spoiler_level == 0


def test_invalid_spoiler_level_raises():
    bad = {**VALID_CHARACTER_MAP}
    bad["characters"] = [{**VALID_CHARACTER_MAP["characters"][0], "spoiler_level": 5}]
    with pytest.raises(ValidationError):
        CharacterMap.model_validate(bad)


def test_missing_spoiler_level_allowed_with_none():
    """spoiler_level is Optional — missing → None, pipeline sweeps to 3."""
    bad = {**VALID_CHARACTER_MAP}
    char = {k: v for k, v in VALID_CHARACTER_MAP["characters"][0].items() if k != "spoiler_level"}
    bad["characters"] = [char]
    result = CharacterMap.model_validate(bad)
    assert result.characters[0].spoiler_level is None


def test_invalid_importance_raises():
    bad = {**VALID_CHARACTER_MAP}
    bad["characters"] = [{**VALID_CHARACTER_MAP["characters"][0], "importance": "hero"}]
    with pytest.raises(ValidationError):
        CharacterMap.model_validate(bad)


def test_invalid_relationship_type_raises():
    bad = {**VALID_CHARACTER_MAP}
    bad["relationships"] = [{**VALID_CHARACTER_MAP["relationships"][0], "type": "enemy"}]
    with pytest.raises(ValidationError):
        CharacterMap.model_validate(bad)


def test_refusal_unknown_work_parses():
    r = RefusalResponse.model_validate({"refusal": "unknown_work"})
    assert r.refusal == "unknown_work"


def test_refusal_low_confidence_parses():
    r = RefusalResponse.model_validate({"refusal": "low_confidence"})
    assert r.refusal == "low_confidence"


def test_refusal_policy_parses():
    r = RefusalResponse.model_validate({"refusal": "policy"})
    assert r.refusal == "policy"


def test_refusal_custom_parses():
    r = RefusalResponse.model_validate({"refusal": "some_future_code"})
    assert r.refusal == "some_future_code"


def test_setting_preamble_optional():
    result = CharacterMap.model_validate(VALID_CHARACTER_MAP)
    assert result.setting_preamble is None


def test_coverage_note_optional():
    result = CharacterMap.model_validate(VALID_CHARACTER_MAP)
    assert result.coverage_note is None
