import json
import pytest
from pydantic import ValidationError
from unittest.mock import AsyncMock
from app.llm.base import LLMResult
from app.worker.pipeline import RefusalError, call_and_validate

VALID_MAP_JSON = json.dumps({
    "title": "Congo",
    "subtitle": "Michael Crichton, 1980",
    "blurb": "An expedition into the Congo.",
    "spoiler_mode": "full",
    "factions": [{"id": "erts", "label": "ERTS", "description": "The expedition.", "color_hint": "blue"}],
    "characters": [{
        "id": "peter",
        "name": "Peter Elliot",
        "role": "Primatologist",
        "description": "UC Berkeley professor.",
        "faction_id": "erts",
        "importance": "protagonist",
        "is_deceased_in_work": False,
        "spoiler_level": 0,
    }],
    "relationships": [],
    "notes": "Generated by Character Map Generator.",
})

INVALID_JSON = '{"title": "Congo", "missing_required_fields": true}'


def _make_client(*texts: str) -> AsyncMock:
    """Return a mock LLM client that yields texts in order."""
    call_count = 0

    async def generate(system_prompt, user_message, max_tokens=4096):
        nonlocal call_count
        result = LLMResult(
            text=texts[call_count],
            input_tokens=100,
            output_tokens=200,
            cost_usd=0.01,
        )
        call_count += 1
        return result

    mock = AsyncMock()
    mock.generate_character_map.side_effect = generate
    return mock


@pytest.mark.asyncio
async def test_valid_on_first_try():
    client = _make_client(VALID_MAP_JSON)
    char_map, llm_result = await call_and_validate(client, "system", "user")
    assert char_map.title == "Congo"
    assert client.generate_character_map.call_count == 1


@pytest.mark.asyncio
async def test_invalid_first_then_valid_retries_once():
    client = _make_client(INVALID_JSON, VALID_MAP_JSON)
    char_map, llm_result = await call_and_validate(client, "system", "user")
    assert char_map.title == "Congo"
    assert client.generate_character_map.call_count == 2


@pytest.mark.asyncio
async def test_two_invalid_responses_raises():
    client = _make_client(INVALID_JSON, INVALID_JSON)
    with pytest.raises(ValidationError):
        await call_and_validate(client, "system", "user")
    assert client.generate_character_map.call_count == 2


@pytest.mark.asyncio
async def test_refusal_unknown_work_raises():
    client = _make_client('{"refusal": "unknown_work"}')
    with pytest.raises(RefusalError) as exc_info:
        await call_and_validate(client, "system", "user")
    assert exc_info.value.refusal_code == "unknown_work"


@pytest.mark.asyncio
async def test_refusal_low_confidence_raises():
    client = _make_client('{"refusal": "low_confidence"}')
    with pytest.raises(RefusalError) as exc_info:
        await call_and_validate(client, "system", "user")
    assert exc_info.value.refusal_code == "low_confidence"


@pytest.mark.asyncio
async def test_refusal_policy_raises():
    client = _make_client('{"refusal": "policy"}')
    with pytest.raises(RefusalError) as exc_info:
        await call_and_validate(client, "system", "user")
    assert exc_info.value.refusal_code == "policy"


@pytest.mark.asyncio
async def test_refusal_does_not_retry():
    """Refusals are terminal — we must not retry them."""
    client = _make_client('{"refusal": "unknown_work"}', VALID_MAP_JSON)
    with pytest.raises(RefusalError):
        await call_and_validate(client, "system", "user")
    assert client.generate_character_map.call_count == 1


@pytest.mark.asyncio
async def test_spoiler_level_none_survives_validation():
    """Pipeline must sweep None spoiler_levels to 3 after this returns."""
    map_without_spoiler = json.loads(VALID_MAP_JSON)
    del map_without_spoiler["characters"][0]["spoiler_level"]
    client = _make_client(json.dumps(map_without_spoiler))
    char_map, _ = await call_and_validate(client, "system", "user")
    assert char_map.characters[0].spoiler_level is None  # sweep happens in run_pipeline


@pytest.mark.asyncio
async def test_fenced_json_parses_on_first_try():
    """Haiku 4.5 wraps JSON in ```json fences — strip and parse without retry."""
    fenced = f"```json\n{VALID_MAP_JSON}\n```"
    client = _make_client(fenced)
    char_map, _ = await call_and_validate(client, "system", "user")
    assert char_map.title == "Congo"
    assert client.generate_character_map.call_count == 1


@pytest.mark.asyncio
async def test_fenced_json_no_language_tag():
    """Fence without `json` language hint should also be stripped."""
    fenced = f"```\n{VALID_MAP_JSON}\n```"
    client = _make_client(fenced)
    char_map, _ = await call_and_validate(client, "system", "user")
    assert char_map.title == "Congo"
    assert client.generate_character_map.call_count == 1


@pytest.mark.asyncio
async def test_fenced_refusal_raises_refusal_not_validation():
    """A fenced refusal must surface as RefusalError, not invalid_json."""
    fenced = '```json\n{"refusal": "unknown_work"}\n```'
    client = _make_client(fenced)
    with pytest.raises(RefusalError) as exc_info:
        await call_and_validate(client, "system", "user")
    assert exc_info.value.refusal_code == "unknown_work"
    assert client.generate_character_map.call_count == 1


@pytest.mark.asyncio
async def test_fenced_invalid_then_unfenced_valid_retries():
    """Fenced *invalid* JSON should still trigger the retry path."""
    fenced_invalid = f"```json\n{INVALID_JSON}\n```"
    client = _make_client(fenced_invalid, VALID_MAP_JSON)
    char_map, _ = await call_and_validate(client, "system", "user")
    assert char_map.title == "Congo"
    assert client.generate_character_map.call_count == 2


@pytest.mark.asyncio
async def test_unfenced_output_unchanged():
    """Strip is a no-op for fence-free output (Sonnet/Opus path)."""
    client = _make_client(VALID_MAP_JSON)
    char_map, _ = await call_and_validate(client, "system", "user")
    assert char_map.title == "Congo"
    assert client.generate_character_map.call_count == 1
