import bleach
from app.models.character_map import CharacterMap


def _clean(text: str) -> str:
    return bleach.clean(text, tags=[], strip=True)


def render_markdown(char_map: CharacterMap) -> str:
    lines: list[str] = []

    lines += [f"# {_clean(char_map.title)}", f"## {_clean(char_map.subtitle)}", ""]
    lines += [_clean(char_map.blurb), ""]

    if char_map.coverage_note:
        lines += [f"> ⚠ **Coverage note:** {_clean(char_map.coverage_note)}", ""]

    if char_map.setting_preamble:
        lines += ["## Setting", "", _clean(char_map.setting_preamble), ""]

    char_by_id = {c.id: c for c in char_map.characters}

    for faction in char_map.factions:
        lines += [f"## {_clean(faction.label)}", "", _clean(faction.description), ""]
        for char in char_map.characters:
            if char.faction_id != faction.id:
                continue
            dagger = " †" if char.is_deceased_in_work else ""
            lines += [
                f"**{_clean(char.name)}{dagger}** *({char.importance})*",
                "",
                _clean(char.description),
                "",
            ]

    if char_map.relationships:
        lines += ["## Relationships", "", "| From | To | Type | Notes |", "|------|----|------|-------|"]
        for rel in char_map.relationships:
            from_name = _clean(char_by_id[rel.from_id].name) if rel.from_id in char_by_id else rel.from_id
            to_name = _clean(char_by_id[rel.to_id].name) if rel.to_id in char_by_id else rel.to_id
            lines.append(f"| {from_name} | {to_name} | {rel.type} | {_clean(rel.label)} |")
        lines.append("")

    lines += ["---", "", f"*{_clean(char_map.notes)}*", ""]
    lines.append(
        "This map contains full spoilers. Generated by Character Map Generator."
    )
    return "\n".join(lines)
