import bleach
from app.models.character_map import Character, CharacterMap, CreatorInfo


def _clean(text: str) -> str:
    return bleach.clean(text, tags=[], strip=True)


_CREATOR_PREFIX = {"author": "By", "director": "Directed by"}


def _creator_line(creator: CreatorInfo) -> str:
    prefix = _CREATOR_PREFIX.get(creator.kind, "By")
    name = _clean(creator.name)
    if creator.headshot_url:
        return f"**{prefix}:** ![{name}]({creator.headshot_url}) {name}"
    return f"**{prefix}:** {name}"


def _character_block(char: Character) -> list[str]:
    dagger = " †" if char.is_deceased_in_work else ""
    name = _clean(char.name)
    header = f"**{name}{dagger}** *({char.importance})*"
    block: list[str] = []
    if char.actor is not None:
        actor_name = _clean(char.actor.name)
        header += f" — played by {actor_name}"
        block.append(header)
        block.append("")
        if char.actor.headshot_url:
            block.append(f"![{name} as played by {actor_name}]({char.actor.headshot_url})")
            block.append("")
    else:
        block.append(header)
        block.append("")
    block.append(_clean(char.description))
    block.append("")
    return block


def render_markdown(char_map: CharacterMap) -> str:
    lines: list[str] = []

    lines += [f"# {_clean(char_map.title)}", f"## {_clean(char_map.subtitle)}", ""]
    if char_map.creator:
        lines += [_creator_line(char_map.creator), ""]
    lines += [_clean(char_map.blurb), ""]

    if char_map.coverage_note:
        lines += [f"> ⚠ **Coverage note:** {_clean(char_map.coverage_note)}", ""]

    if char_map.setting_preamble:
        lines += ["## Setting", "", _clean(char_map.setting_preamble), ""]

    char_by_id = {c.id: c for c in char_map.characters}

    for faction in char_map.factions:
        lines += [f"## {_clean(faction.label)}", "", _clean(faction.description), ""]
        for char in char_map.characters:
            if char.faction_id != faction.id:
                continue
            lines += _character_block(char)

    if char_map.relationships:
        lines += ["## Relationships", "", "| From | To | Type | Notes |", "|------|----|------|-------|"]
        for rel in char_map.relationships:
            from_name = _clean(char_by_id[rel.from_id].name) if rel.from_id in char_by_id else rel.from_id
            to_name = _clean(char_by_id[rel.to_id].name) if rel.to_id in char_by_id else rel.to_id
            lines.append(f"| {from_name} | {to_name} | {rel.type} | {_clean(rel.label)} |")
        lines.append("")

    lines += ["---", "", f"*{_clean(char_map.notes)}*", ""]
    lines.append(
        "This map contains full spoilers. Generated by Character Map Generator."
    )
    if _uses_tmdb_data(char_map):
        lines += [
            "",
            "This product uses the TMDB API but is not endorsed or certified by TMDB. Photos and adaptation data: TMDb.",
        ]
    return "\n".join(lines)


def _uses_tmdb_data(char_map: CharacterMap) -> bool:
    if char_map.creator and char_map.creator.kind == "director":
        return True
    return any(c.actor is not None for c in char_map.characters)
